* 顾比均线组

  顾比均线是有澳大利亚的 戴若.顾比 发明的一套用于研判股票发展趋势的有短期和长期两部分组成的均线组。

  在顾比均线的理论中，市场由交易者和投资者两部分人群组成。

  交易者，是典型的追涨杀跌的群体。当趋势向好的时候，交易者迫切的希望持有股票，从而快速推升了股票的价格；而当趋势一旦发生变化，交易者会竞相卖出股票以保护利润，因此股价会迅速回落。交易者是以交易股票获取短期利润为目标的，关注的重点是不赔钱。交易者的存在，使得股价围绕价值剧烈的波动。

  投资者是相对温和的群体，他们会花费更多的时间认识趋势中的变化。也总是跟在交易者的后面进行股票的买卖。股票上升趋势的维持，需要在投资者进入市场之后才会得以维持。而强的趋势也是有长期投资者支撑的。

  针对上面的两类人群，可以使用6条短期移动平均线来表示交易者的行为；用6条长期移动平均线来表示投资者的行为。

** 移动平均线（短期组和长期组）

   短期组由3、5、8、10、12、15等6条均线组成。长期组由30、35、40、45、50、60等6条均线组成。
   为了让均线对于近期的价格反应更加灵敏，可以使用EMA（指数移动平均）的方式来计算各个均线组。

** 顾比均线所表示的趋势的转折

   当顾比均线组所表示的趋势发生转折的时候，均线组的收敛是必然的结果。在数学上，表现为均线组宽度的缩小。

   当均线组宽度由缩小转为放大时，一个新的趋势就开始了（可能是上升、也可能是下降）。

   目前的代码实现上，我们还没有将趋势转折的过渡期完成有效的定义。如果能够实现过渡期的定义，那么对于预警个股趋势的变化将是非常有用的。

* 源代码

  以每天的收盘价格定义短期均线组。默认情况下，使用红色进行绘制。

  #+BEGIN_SRC text :tangle yes
    E3:EMA(C,3),COLORRED;
    E5:EMA(C,5),COLORRED;
    E8:EMA(C,8),COLORRED;
    E10:EMA(C,10),COLORRED;
    E12:EMA(C,12),COLORRED;
    E15:EMA(C,15),COLORRED;
  #+END_SRC

  重绘其中下降趋势的部分。对于下降部分，使用绿色进行绘制

  #+BEGIN_SRC text :tangle yes
    PartLine(E3<Ref(E3,3) Or E15<Ref(E15,3),E3),ColorGreen;
    PartLine(E5<Ref(E5,3) Or E15<Ref(E15,3),E5),ColorGreen;
    PartLine(E8<Ref(E8,3) Or E15<Ref(E15,3),E8),ColorGreen;
    PartLine(E10<Ref(E10,3) Or E15<Ref(E15,3),E10),ColorGreen;
    PartLine(E12<Ref(E12,3) Or E15<Ref(E15,3),E12),ColorGreen;
    PartLine(E15<Ref(E15,3),E15),ColorGreen;      
  #+END_SRC

  绘制趋势过渡阶段的图线。目前对于过渡阶段的判断还不够精确。

  #+BEGIN_SRC text :tangle yes
    STrans := ( MaxList(E3,E5,E8,E10,E12,E15)-MinList(E3,E5,E8,E10,E12,E15) < 
                MaxList(Ref(E3,3),Ref(E5,3),Ref(E8,3),Ref(E10,3),Ref(E12,3),Ref(E15,3)) - 
                        MinList(Ref(E3,3),Ref(E5,3),Ref(E8,3),Ref(E10,3),Ref(E12,3),Ref(E15,3))                     
                      );
    PartLine(STrans,E3),ColorBlue;
    PartLine(STrans,E5),ColorBlue;
    PartLine(STrans,E8),ColorBlue;
    PartLine(STrans,E10),ColorBlue;
    PartLine(STrans,E12),ColorBlue;
    PartLine(STrans,E15),ColorBlue;
  #+END_SRC

  绘制长期均线组
  #+BEGIN_SRC text :tangle yes
    E30:EMA(C,30),ColorBrown;
    E35:EMA(C,35),ColorBrown;
    E40:EMA(C,40),ColorBrown;
    E45:EMA(C,45),ColorBrown;
    E50:EMA(C,50),ColorBrown;
    E60:EMA(C,60),ColorBrown;
  #+END_SRC

  绘制长期均线组的下降部分
  #+BEGIN_SRC text :tangle yes
    PartLine(E3<Ref(E3,3) Or E15<Ref(E15,3),E3),ColorGreen;
    PartLine(E5<Ref(E5,3) Or E15<Ref(E15,3),E5),ColorGreen;
    PartLine(E8<Ref(E8,3) Or E15<Ref(E15,3),E8),ColorGreen;
    PartLine(E10<Ref(E10,3) Or E15<Ref(E15,3),E10),ColorGreen;
    PartLine(E12<Ref(E12,3) Or E15<Ref(E15,3),E12),ColorGreen;
    PartLine(E15<Ref(E15,3),E15),ColorGreen;
  #+END_SRC

  绘制长期均线组转折阶段
  #+BEGIN_SRC text :tangle yes
    LTrans := ( MaxList(E30,E35,E40,E45,E50,E60)-MinList(E30,E35,E40,E45,E50,E60) < 
                MaxList(Ref(E30,1),Ref(E35,1),Ref(E40,1),Ref(E45,1),Ref(E50,1),Ref(E60,1)) - 
                MinList(Ref(E30,1),Ref(E35,1),Ref(E40,1),Ref(E45,1),Ref(E50,1),Ref(E60,1))
              );
    PartLine(LTrans,E30),ColorYellow;
    PartLine(LTrans,E35),ColorYellow;
    PartLine(LTrans,E40),ColorYellow;
    PartLine(LTrans,E45),ColorYellow;
    PartLine(LTrans,E50),ColorYellow;
    PartLine(LTrans,E60),ColorYellow;          
  #+END_SRC
  
  重新绘制K线图
  #+BEGIN_SRC text :tangle yes
    STICKLINE(C>O,C,O,8,1),COLORRED;
    STICKLINE(C>O,C,H,0.8,1),COLORRED;
    STICKLINE(C>O,O,L,0.8,1),COLORRED;
    STICKLINE(C<=O,C,O,8,0),COLORFFFF52;
    STICKLINE(C<=O,H,L,0.8,1),COLORFFFF52;
  #+END_SRC
