#+TITLE: 阅读《构建你的盈利系统》

* 盈利系统基本概念

** 基本概念

*** 投资知识

    构建盈利系统，需要具备与投资相关的诸多知识：金融经济类、企业管理类、
    技术分析类、宗教哲学类。其目的在于理解“市场的本质”，以及“中国市
    场的本质”，发现价格运行的内在规律，为自己的投资获利服务。 

    成功的经验值得发扬，失败的教训也是发现弱点、改进不足、扬长避短的智
    力基础。 

*** 投资策略
   
**** 构建股票池

     这是第一步，通过某种方法将可能上涨的股票找出来，是这一步的关键 

**** 进场时机

     找到最可能上涨的股票的最合适的买入点

**** 投资组合

     即买入多少只股票，什么样的股票。由于中国股市的板块轮动特点，构建投
     资组合时不宜将所有资金几种在同类板块。同时，需要控制股票数量在合理
     的范围内。 

**** 资金进场比例

     从防范风险的角度考虑，进场需要试探，在确定安全时再全线杀入。资金进
     场比例控制是进行整体风险防范的重要手段。 

**** 止损位

     为避免做错后资金进一步亏损而采取的保护措施。具体可以是关键支撑位、
     固定比例、均线死叉等技术方法来确定.

**** 出场时机

     即卖出时机。对买入的股票在合理的价格出手离场。出场时机可以是止赢，
     也可以是止损。在小明的操作体系中，也可能是对于买入理由消失的时候的
     一种纠错操作。 

*** 投资心理

    任何一个投资者的投资行为都是心理活动的结果。都是对市场、人气、基本
    面等所有信息分析和判断以后的投资决策。因此，投资者的情绪、知觉、态
    度、信念等都会影响投资行为和投资结果。已经证明：人在面临资金的决策
    往往是不理智的、非理性的，构建一个全新的心智模式，主要目的是为了
    “理解自己、正视自己的错误、改正自己的错误。” 

*** 总和

   盈利系统是多种知识的应用后创造出来的投资工具。具有鲜明的个人心理特
   征。因此每个人构建的盈利系统都不一样。同样的盈利系统不同人使用的结
   果也是不一样的。

** 盈利系统的六边形

   任何一个成功的盈利系统，都需要从六个方面考虑验证
   
   1. 交易机会的次数

      是系统发出买入、卖出信号的次数。不同类型的交易者构建的盈利系统发
      出信号的次数明显是不同的。显然，短线交易系统发出的信号多，而长线
      交易系统发出的信号会明显少。

   2. 资金的使用比例

      投资有风险，入市需谨慎。在资金规模确定的情况下，资金的使用比例决
      定了盈利的规模也应承担相应的亏损。即，在全额使用资金的情况下，一
      旦盈利，固然获取的利润是最多的，但发生亏损的情况下，亏损的金额也
      是最大的。因此资金的使用比例是一个双刃剑，需要仔细考虑。

   3. 加减仓的技巧

      由于股价的变动不是直线式的，而呈现出波浪式，随机性等特点，因此加
      减仓时可以考虑采用分批次的方式进行。

   4. 交易成本

      交易成本主要包括：佣金、印花税和心理成本。心理成本主要是由于交易
      过程中投入时间、精力、压力等因素带来的。在心理成本巨大的情况下，
      交易可能会出现偏差。

   5. 盈亏比

      盈亏比是每次买卖的收益与亏损的比值。投资1万元，若盈利2000元，发生
      亏损则亏损1000元时，盈亏比则为2:1 。显然盈亏比大的交易系统更为优
      秀。

   6. 胜算（可靠性）

      胜算是交易系统发出信号后，据此操作盈利的次数与亏损次数的比值。如
      果一个系统一年发出100次交易指令，其中80次是盈利的，20次是亏损的，
      则这个系统的胜算是80:20，即，4:1。

      可靠性是胜算的另一种说法。在上面的例子中，交易系统的可靠性为80%。

      胜算与盈亏比是同等重要的指标。一般而言，

      总获利=（盈利的次数 * 平均每次盈利的金额） - （ 亏损的次数 * 平均
      每次亏损的金额）

      总获利高，是构建/修正盈利系统的目标。




* 盈利系统的特征

** 任何盈利系统无法保证“在最低点买入， 最高点卖出”

   1. 最高点和最低点是时候得知的。

      没有股价的后续变化，我们不知道前期的点是所谓的高点还是低点。只有
      下跌，才知道那是高点，是顶部；只有跌下去，才会确定那是一个最高点。
      对于最低点的判断也是如此。

   2. 最高点和最低点往往是阶段性的高点和低点

      地板下还有地下室呢

   3. 最高点和最低点的成交量往往是有限的

      理解交易的本质，在那个价位上不可能永远成交下去。


   因此，可以做到的是“在较低的位置买入， 在较高的位置卖出”。而无法期
   待在“最低点买入，最高点卖出”

   
** 盈利系统应能帮助选股

   盈利系统应可以根据某些标准，完成股票筛选功能，建立相应的股票池

** 盈利系统应帮助择时

   即选择买入和卖出的时机。选择买入时机尽可能在低位，选择卖出时机尽可
   能在高位。

   但由于高位和低位的判断是属于 “未来函数” 确定的，可能需要结合更多
   的技术参数（例如大盘当前位置）来对高低位进行定性判断

** 盈利系统应有纠错功能

   当选股错误或选时不当时，可能出现亏损或丢趋势的情况出现。因此在操作
   系统中，纠错非常重要。

   纠错，是对上一次操作的纠正。即，当我们买入后，纠错是进行卖出操作。
   我们卖出后，纠错是买入操作。

   纠错，与止损带来的纠错具有一定程度上的重合。但纠错关注的是上一次买
   卖操作的理由是否继续成立。当理由消失的时候，进行纠错操作。而止损关
   注的是单只股票的波动情况。当超出风险承受能力的时候进行止损卖出操作。

   注意纠错、止损、离场（止赢）三个概念在哪些地方是重合的，又有什么不
   一样的地方。

** 盈利系统具有核心交易规则

   盈利系统的核心规则：

   1. 建立系统

      说明系统市场的市场类型：股票？期货（商品期货、贵金属期货）？外汇？
      等

   2. 管理风险

      风险，是指一切可能导致投资者破产的风险。盈亏比和胜率是管理风险的
      重要武器。资金比例控制在使用融资融券的时候非常重要，避免爆仓强平。

   3. 坚定不移

      主要强调盈利系统的自信心和操盘行为的自我控制能力，是一种执行力。

   4. 简单明了

      不应建立的过于复杂。尤其是避免引入过多的技术指标，避免指标冲突时
      的犹豫不定。
      我认为如何处理指标冲突，是构建盈利系统的一个难点。（小明的“趋势为王，
      结构修边”就是对指标冲突的一种处理方法）。

** 盈利系统应保证收益率 

   书上写的内容，我不是非常认同。固定的收益率指标在下跌的年份中可能无
   法达成。这不能说明交易系统存在问题。不见各个基金的收益率均参照大盘
   而设定的吗？

   我认为跑赢大盘是设计盈利系统的重要评估指标之一。

* 


* 关于择时

  趋势与结构相冲突的时候，应该应该以趋势为标准进行买入

  如果趋势突破，与大级别的结构钝化冲突时（趋势突破与结构形成不在同一个时间），应该先买入，在结构形成时再卖出

* 关于择股

* 关于买入时机的把握

* 关于卖出时机的把握

  卖出股票的标准： 

  * 跌破顾比倒数止损线
  * MACD出现死叉
    当MACD于0轴上方形成死叉时，有可能是主力在洗盘，因此需要考虑卖出的纠错问题


** 操作方法

   当MACD在0轴上方形成死叉时，卖出一半，如果绿脚线明显放大，则全部卖出。
   

* 关于纠错

